name: Deploy
on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install and Build
        run: |
          echo "Install Requirements."
          sudo apt update
          sudo apt-get update
          brew update && brew upgrade
          sudo apt install rbenv
          sudo apt-get install autoconf bison patch build-essential rustc libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libgmp-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev uuid-dev
          rbenv install 3.1.2
          rbenv global 3.1.2
          sudo gem install bundler
          #sudo apt install -y ruby ruby-dev build-essential libffi-dev zlib1g-dev liblzma-dev nodejs patch
          #sudo gem update --system
          #sudo gem install bundler
          cd ./slate_project && bundle install && cd ..
          npm install drafter
          echo "Running install script"
          sh update.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: main
          folder: docs
          clean: true
          clean-exclude: |
            */*.json
          target-folder: 'docs'
          
