name: Deploy
on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'    
        
      - name: Install and Build
        run: |
          echo "Install Requirements."
          sudo apt update          
          #sudo apt install -y ruby ruby-dev build-essential libffi-dev zlib1g-dev liblzma-dev nodejs patch
          sudo gem update --system
          sudo gem install bundler
          cd ./slate_project && bundle install && cd ..
          npm install drafter
          echo "Running install script"
          sh update.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: main
          folder: docs
          clean: true
          clean-exclude: |
            */*.json
          target-folder: 'docs'
          
