name: Deploy
on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Ruby
        run: |
          wget -O ruby-install-0.8.5.tar.gz https://github.com/postmodern/ruby-install/archive/v0.8.5.tar.gz
          tar -xzvf ruby-install-0.8.5.tar.gz
          cd ruby-install-0.8.5/
          sudo make install
          ruby-install ruby
          
      - name: Install and Build
        run: |
          echo "Install Requirements."
          sudo apt update          
          #sudo apt install -y ruby ruby-dev build-essential libffi-dev zlib1g-dev liblzma-dev nodejs patch
          sudo gem update --system
          sudo gem install bundler
          cd ./slate_project && bundle install && cd ..
          npm install drafter
          echo "Running install script"
          sh update.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: main
          folder: docs
          clean: true
          clean-exclude: |
            */*.json
          target-folder: 'docs'
          
